[package]
name = "livekit-api"
version = "0.1.0"
edition = "2021"

[dependencies]
jsonwebtoken = {version = "8", default-features = false }
thiserror = "1.0"
serde = {version = "1.0", features = ["derive"] }
serde_json = "1.0"
livekit-protocol = { path = "../livekit-protocol", version = "0.1.0" }
sha2 = "0.10.6"
reqwest = { version = "0.11", default-features=false, features=["json", "rustls", "rustls-tls"] }
url = "2.3.1"
prost = "0.11.9"
