[package]
name = "webrtc-sys"
version = "0.1.1"
edition = "2021"
homepage = "https://livekit.io"
license = "Apache-2.0"
description = "Unsafe bindings to libwebrtc"
repository = "https://github.com/livekit/client-sdk-rust" 

[dependencies]
cxx = "1.0"
log = "0.4"

[build-dependencies]
reqwest = { version = "0.11", features = ["blocking", "json", "rustls", "rustls-tls"] }
tar = "0.4"
flate2 = "1.0"
cxx-build = "1.0"
glob = "0.3.0"
regex = "1.0"
zip = "0.6.3"

[dev-dependencies]
env_logger = "0.10"

#[lib]
#crate-type = ["staticlib", "cdylib"]
